notifications:
  email: sanssecours@me.com

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4

before_install:

  # ==========
  # = Python =
  # ==========

  - brew install python3
  - sudo pip3 install cram flake8 nose tox

  # ========
  # = Ruby =
  # ========

  - rvm list
  - rvm install 2.4.1; rvm use 2.4.1
  - gem install rubydoctest rubocop

  # ========
  # = Perl =
  # ========

  - curl -L http://cpanmin.us | perl - App::cpanminus
  - export PATH=$PATH:"$HOME/perl5/bin"
  - export PERL5LIB="$HOME/perl5/lib/perl5"
  - cpanm Perl::Critic

  # =======
  # = TeX =
  # =======

  - curl -L http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg -O
  - sudo installer -pkg BasicTeX.pkg -target /
  - export PATH=$PATH:/Library/TeX/texbin:/usr/texbin
  - sudo tlmgr update --self --all
  - >-
    sudo tlmgr install
    biber biblatex csquotes ctablestack datatool framed glossaries latexmk
    logreq luacode mfirstuc substr supertabular texdoc xfor xstring

  # ================
  # = Applications =
  # ================

  - brew cask install skim
  - brew install ghostscript pidof

  # ============
  # = TextMate =
  # ============

  - brew cask install textmate
  - open /Applications/TextMate.app

  - mkdir -p "$HOME/bin"
  - cd "$HOME/bin"
  - curl -L http://updates.textmate.org/gtm.bz2 -O
  - bzip2 -d gtm.bz2
  - chmod u+x gtm

  - cd "$HOME/Library/Application Support"
  - mkdir -p TextMate; cd TextMate
  - mkdir -p Managed; cd Managed
  - mkdir -p Bundles; cd Bundles
  - git clone https://github.com/textmate/java.tmbundle.git
  - git clone https://github.com/textmate/javadoc.tmbundle.git
  - git clone https://github.com/textmate/r.tmbundle.git

before_script:
  - cd "$TRAVIS_BUILD_DIR"

script:
  - make
